Repository Broken-Gem-Studio/Broken-Engine, pull requests merged in 2020-05, with the labels that each got.

#314 solved dt and instantiate bugs
  Broken Engine/Source/ModulePhysics.cpp
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ModuleTimeManager.cpp
  Broken Engine/Source/ScriptingScenes.cpp
Labels: Bug

#301 Ui improvements
  Broken Engine/Source/ComponentButton.cpp
  Broken Engine/Source/ComponentCanvas.cpp
  Broken Engine/Source/ComponentCanvas.h
  Broken Engine/Source/ComponentCircularBar.cpp
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentProgressBar.cpp
  Broken Engine/Source/ComponentText.cpp
  Broken Engine/Source/ModuleUI.cpp
Labels: Enhancement

#302 partial transparencies working
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/PanelRendering.cpp
  Broken Engine/Source/PanelRendering.h
Labels: Enhancement

#327 fixed ui canvas movement
  Broken Engine/Source/ComponentButton.cpp
  Broken Engine/Source/ComponentCanvas.cpp
  Broken Engine/Source/ComponentCircularBar.cpp
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentProgressBar.cpp
  Broken Engine/Source/ComponentText.cpp
Labels: Bug

#324 Preview Screenshot Flicker
  Broken Engine/Source/ModuleRenderer3D.cpp
Labels: Bug, Low Priority

#320 prefab now saves static and active bools, and acts accordingly on load
  Broken Engine/Source/ImporterModel.cpp
  Broken Engine/Source/ImporterPrefab.cpp
  Broken Engine/Source/ImporterScene.cpp
Labels: Bug, Enhancement

#329 Audio Interactive Music Support
  Broken Engine/Game/Assets/Sounds/Init.bnk
  Broken Engine/Game/Assets/Sounds/Init.json
  Broken Engine/Game/Assets/Sounds/Init.xml
  Broken Engine/Game/Assets/Sounds/Wwise_IDs.h
  Broken Engine/Source/ModuleAudio.cpp
  Broken Engine/Source/ModuleAudio.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingAudio.cpp
  Broken Engine/Source/ScriptingAudio.h
Labels: Enhancement

#345 panel project assets explorer scrollbar
  Broken Engine/Source/PanelProject.cpp
Labels: Enhancement, Low Priority

#343 console auto-scrolling again
  Broken Engine/Source/PanelConsole.cpp
Labels: Bug, Low Priority

#338 Scripting with relative paths
  Broken Engine/Source/ImporterScript.cpp
  Broken Engine/Source/ModuleFileSystem.cpp
  Broken Engine/Source/ModuleFileSystem.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ModuleScripting.h
  Broken Engine/Source/PanelProject.cpp
Labels: Enhancement

#340 Skybox rotation
  Broken Engine/Game/Assets/Shaders/SkyboxShader.glsl
  Broken Engine/Game/Settings/EditorConfig.json
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/PanelRendering.cpp
Labels: Enhancement

#341 can now specify name on resource creation
  Broken Engine/Source/PanelProject.cpp
  Broken Engine/Source/PanelProject.h
Labels: Enhancement

#353 Fixed screenshader and now engine uses screenshader
  Broken Engine/Game/Assets/Shaders/ScreenShader.glsl
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
Labels: Enhancement

#296 Reverted euler angles back to old behaviour
  Broken Engine/Source/ComponentTransform.cpp
Labels: Bug

#359 Animations Scripting Functions
  Broken Engine/Source/AutoCompleteFileGen.cpp
  Broken Engine/Source/ComponentAnimation.cpp
  Broken Engine/Source/ComponentAnimation.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingAnimations.cpp
  Broken Engine/Source/ScriptingAnimations.h
Labels: Enhancement

#358 UI Alpha/Color Change from Scripting
  Broken Engine/Source/ComponentButton.h
  Broken Engine/Source/ComponentCircularBar.h
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentImage.h
  Broken Engine/Source/ComponentProgressBar.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingInterface.cpp
  Broken Engine/Source/ScriptingInterface.h
Labels: Enhancement

#357 New shadow mapping
  Broken Engine/Game/Assets/Shaders/ShadowsShader.glsl
  Broken Engine/Game/Assets/Shaders/Standard.glsl
  Broken Engine/Game/Settings/EditorConfig.json
  Broken Engine/Source/AutoCompleteFileGen.cpp
  Broken Engine/Source/Broken Engine.vcxproj
  Broken Engine/Source/Broken Engine.vcxproj.filters
  Broken Engine/Source/ComponentButton.cpp
  Broken Engine/Source/ComponentCircularBar.cpp
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentLight.cpp
  Broken Engine/Source/ComponentLight.h
  Broken Engine/Source/ComponentMeshRenderer.cpp
  Broken Engine/Source/ComponentMeshRenderer.h
  Broken Engine/Source/ComponentProgressBar.cpp
  Broken Engine/Source/ComponentText.cpp
  Broken Engine/Source/ModuleEditorUI.cpp
  Broken Engine/Source/ModuleEditorUI.h
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ModuleSelection.cpp
  Broken Engine/Source/PanelHierarchy.cpp
  Broken Engine/Source/PanelRendering.cpp
  Broken Engine/Source/PanelShadowedScene.cpp
  Broken Engine/Source/PanelShadowedScene.h
  Broken Engine/Source/Panels.h
  Broken Engine/Source/Particle.cpp
  Broken Engine/Source/ResourceShader.cpp
  Broken Engine/Source/ScriptingLighting.cpp
  Broken Engine/Source/ScriptingLighting.h
Labels: Enhancement, High Priority

#360 Particles fixes & small implementations
  Broken Engine/Source/ComponentParticleEmitter.cpp
  Broken Engine/Source/ComponentParticleEmitter.h
  Broken Engine/Source/ModuleParticles.cpp
  Broken Engine/Source/ModuleParticles.h
  Broken Engine/Source/Particle.h
Labels: Bug, Enhancement

#364 solved crash with canvas (dangling pointer)
  Broken Engine/Source/ComponentButton.h
  Broken Engine/Source/ComponentCanvas.cpp
  Broken Engine/Source/ComponentCanvas.h
  Broken Engine/Source/ComponentCircularBar.h
  Broken Engine/Source/ComponentImage.h
  Broken Engine/Source/ComponentProgressBar.h
  Broken Engine/Source/ComponentText.h
  Broken Engine/Source/UI_Element.h
Labels: Bug, High Priority

#367 New ui animations
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentImage.h
Labels: Enhancement, High Priority

#368 button and progress bar animations working
  Broken Engine/Source/ComponentButton.cpp
  Broken Engine/Source/ComponentButton.h
  Broken Engine/Source/ComponentProgressBar.cpp
  Broken Engine/Source/ComponentProgressBar.h
Labels: Enhancement, High Priority

#373 can now change interactable ui element bool from scripting
  Broken Engine/Source/AutoCompleteFileGen.cpp
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingInterface.cpp
  Broken Engine/Source/ScriptingInterface.h
  Broken Engine/Source/UI_Element.h
Labels: Enhancement, High Priority

#374 Added scripting function to find nearest point in NavMesh to a point
  Broken Engine/Source/AutoCompleteFileGen.cpp
  Broken Engine/Source/ModuleDetour.cpp
  Broken Engine/Source/ModuleDetour.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingNavigation.cpp
  Broken Engine/Source/ScriptingNavigation.h
Labels: Enhancement, High Priority

#380 fix progress bar percentage bug
  Broken Engine/Source/ComponentProgressBar.cpp
Labels: Bug, High Priority

#381 fixed particle crash when deleting the GO
  Broken Engine/Source/ComponentCharacterController.cpp
  Broken Engine/Source/ComponentParticleEmitter.cpp
  Broken Engine/Source/ModuleParticles.cpp
  Broken Engine/Source/ModuleParticles.h
Labels: Bug, High Priority

#383 solve button on click (Save&Load) error
  Broken Engine/Source/ComponentButton.cpp
Labels: Bug, High Priority

#386 Prefab&ModelFileStructureChange
  Broken Engine/Source/ImporterModel.cpp
  Broken Engine/Source/ImporterPrefab.cpp
Labels: DO ASAP, Enhancement, High Priority
