Repository Broken-Gem-Studio/Broken-Engine, pull requests merged in 2020-04, with the labels that each got.

#183 fixed unuse material misbehaviour, issue 165
  Broken Engine/Source/ComponentMeshRenderer.cpp
  Broken Engine/Source/ComponentMeshRenderer.h
Labels: Bug, Medium Priority

#191 solved mistake in importer texture, not updating instances!!
  Broken Engine/Source/ImporterTexture.cpp
Labels: Bug

#192 checking if component is active before drawing, not drawing it is not…
  Broken Engine/Source/GameObject.cpp
Labels: Bug

#198 Prefabs basic implementation
  Broken Engine/Game/Assets/Shaders/LinePoint.glsl
  Broken Engine/Game/Assets/Shaders/OutlineShader.glsl
  Broken Engine/Game/Assets/Shaders/TextShader.glsl
  Broken Engine/Game/Assets/Shaders/ZDrawer.glsl
  Broken Engine/Game/Settings/EditorConfig.json
  Broken Engine/Source/Broken Core.vcxproj
  Broken Engine/Source/Broken Core.vcxproj.filters
  Broken Engine/Source/BrokenEngine.h
  Broken Engine/Source/ComponentMesh.cpp
  Broken Engine/Source/ComponentMeshRenderer.cpp
  Broken Engine/Source/GameObject.cpp
  Broken Engine/Source/GameObject.h
  Broken Engine/Source/Importer.h
  Broken Engine/Source/ImporterMaterial.cpp
  Broken Engine/Source/ImporterModel.cpp
  Broken Engine/Source/ImporterModel.h
  Broken Engine/Source/ImporterPrefab.cpp
  Broken Engine/Source/ImporterPrefab.h
  Broken Engine/Source/Importers.h
  Broken Engine/Source/ModuleCamera3D.cpp
  Broken Engine/Source/ModuleGui.cpp
  Broken Engine/Source/ModuleGui.h
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/ModuleResourceManager.cpp
  Broken Engine/Source/ModuleResourceManager.h
  Broken Engine/Source/ModuleSceneManager.cpp
  Broken Engine/Source/ModuleSceneManager.h
  Broken Engine/Source/ModuleTextures.cpp
  Broken Engine/Source/ModuleTextures.h
  Broken Engine/Source/PanelHierarchy.cpp
  Broken Engine/Source/PanelHierarchy.h
  Broken Engine/Source/PanelProject.cpp
  Broken Engine/Source/PanelProject.h
  Broken Engine/Source/PanelScene.cpp
  Broken Engine/Source/PanelToolbar.cpp
  Broken Engine/Source/Resource.cpp
  Broken Engine/Source/Resource.h
  Broken Engine/Source/ResourceMaterial.cpp
  Broken Engine/Source/ResourceMaterial.h
  Broken Engine/Source/ResourceMesh.cpp
  Broken Engine/Source/ResourceMesh.h
  Broken Engine/Source/ResourceModel.cpp
  Broken Engine/Source/ResourceModel.h
  Broken Engine/Source/ResourcePrefab.cpp
  Broken Engine/Source/ResourcePrefab.h
  Broken Engine/Source/ResourceScene.cpp
  Broken Engine/Source/ResourceScene.h
  Broken Engine/Source/ResourceTexture.cpp
  Broken Engine/Source/ResourceTexture.h
  Broken Engine/Source/Resources.h
Labels: Enhancement, High Priority

#200 Blocked mesh preview
  Broken Engine/Source/ImporterModel.cpp
  Broken Engine/Source/ResourceMesh.cpp
Labels: Bug

#207 Ui fixes
  Broken Engine/Source/ComponentButton.cpp
  Broken Engine/Source/ComponentButton.h
  Broken Engine/Source/ComponentCamera.cpp
  Broken Engine/Source/ComponentCanvas.cpp
  Broken Engine/Source/ComponentCircularBar.cpp
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentProgressBar.cpp
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleUI.cpp
  Broken Engine/Source/ModuleUI.h
  Broken Engine/Source/ModuleWindow.cpp
Labels: Bug

#216 Panel project rename&delete
  Broken Engine/Source/ModuleResourceManager.cpp
  Broken Engine/Source/ModuleResourceManager.h
  Broken Engine/Source/PanelProject.cpp
  Broken Engine/Source/PanelProject.h
  Broken Engine/Source/ResourceModel.cpp
  Broken Engine/Source/ResourceScene.cpp
  Broken Engine/Source/ResourceTexture.cpp
Labels: Enhancement, Low Priority

#223 Build system fix
  .gitignore
  Broken Engine/Source/Application.cpp
  Broken Engine/Source/Application.h
  Broken Engine/Source/BrokenCore.h
  Broken Engine/Source/EngineApplication.cpp
  Broken Engine/Source/EngineApplication.h
  Broken Engine/Source/ModuleFileSystem.cpp
  Broken Engine/Source/ModuleFileSystem.h
  Broken Engine/Source/ModuleTimeManager.cpp
  Broken Engine/Source/PanelBuild.cpp
  Broken Engine/Source/PanelBuild.h
Labels: Bug, DO ASAP

#226 call components load after having created all gos
  Broken Engine/Source/ResourceScene.cpp
Labels: Bug

#234 Fixed rotate object acting like set rotation
  Broken Engine/Source/ComponentCollider.cpp
  Broken Engine/Source/ScriptingTransform.cpp
Labels: Bug, DO ASAP

#248 Fixed GetScript crashing when GO has no component script
  .github/ISSUE_TEMPLATE/bug_issue_template.md
  Broken Engine/Source/ScriptingGameobject.cpp
Labels: Bug, DO ASAP

#252 Basic skybox implementation
  .gitignore
  Broken Engine/Game/Assets/Images/back.jpg
  Broken Engine/Game/Assets/Images/bottom.jpg
  Broken Engine/Game/Assets/Images/front.jpg
  Broken Engine/Game/Assets/Images/left.jpg
  Broken Engine/Game/Assets/Images/right.jpg
  Broken Engine/Game/Assets/Images/top.jpg
  Broken Engine/Game/Assets/Shaders/SkyboxShader.glsl
  Broken Engine/Source/BrokenCore.h
  Broken Engine/Source/ModuleFileSystem.cpp
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/ModuleResourceManager.h
  Broken Engine/Source/ModuleTextures.cpp
  Broken Engine/Source/ModuleTextures.h
Labels: Enhancement

#251 enabled full transparencies, preparing for partial transparency and …
  Broken Engine/Game/Assets/Shaders/LinePoint.glsl
  Broken Engine/Game/Assets/Shaders/Standard.glsl
  Broken Engine/Game/Assets/Shaders/ZDrawer.glsl
  Broken Engine/Game/Settings/EditorConfig.json
  Broken Engine/Source/ComponentButton.cpp
  Broken Engine/Source/ComponentCharacterController.cpp
  Broken Engine/Source/ComponentCircularBar.cpp
  Broken Engine/Source/ComponentImage.cpp
  Broken Engine/Source/ComponentLight.cpp
  Broken Engine/Source/ComponentMeshRenderer.cpp
  Broken Engine/Source/ComponentParticleEmitter.cpp
  Broken Engine/Source/ComponentParticleEmitter.h
  Broken Engine/Source/ComponentProgressBar.cpp
  Broken Engine/Source/ImporterMaterial.cpp
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/Particle.cpp
  Broken Engine/Source/Particle.h
  Broken Engine/Source/ResourceMaterial.cpp
  Broken Engine/Source/ResourceMaterial.h
Labels: Enhancement

#257 Materials save fix
  Broken Engine/Source/Application.cpp
  Broken Engine/Source/Application.h
  Broken Engine/Source/BrokenCore.cpp
  Broken Engine/Source/BrokenCore.h
  Broken Engine/Source/ComponentMeshRenderer.cpp
  Broken Engine/Source/ComponentMeshRenderer.h
  Broken Engine/Source/ImporterMaterial.cpp
  Broken Engine/Source/ModuleRecast.cpp
  Broken Engine/Source/ModuleRecast.h
  Broken Engine/Source/ModuleResourceManager.cpp
  Broken Engine/Source/ModuleResourceManager.h
  Broken Engine/Source/PanelBuild.cpp
  Broken Engine/Source/ResourceMaterial.cpp
Labels: Bug, DO ASAP

#261 solve flicker on model/prefab instancing
  Broken Engine/Source/ImporterModel.cpp
Labels: Bug

#262 Fix engine crashing with bad player ID and others
  Broken Engine/Source/Broken Core.vcxproj.filters
  Broken Engine/Source/ModuleInput.cpp
  Broken Engine/Source/ScriptingInputs.cpp
Labels: Bug, DO ASAP

#264 New functions GetCurrentFrame and SetScale
  Broken Engine/Source/ComponentAnimation.cpp
  Broken Engine/Source/ComponentAnimation.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingAnimations.cpp
  Broken Engine/Source/ScriptingAnimations.h
  Broken Engine/Source/ScriptingTransform.cpp
  Broken Engine/Source/ScriptingTransform.h
Labels: Enhancement

#267 Lighting: Corrections, Improvements & Scripting
  Broken Engine/Game/Assets/Shaders/Standard.glsl
  Broken Engine/Game/Settings/EditorConfig.json
  Broken Engine/Source/Broken Core.vcxproj
  Broken Engine/Source/Broken Core.vcxproj.filters
  Broken Engine/Source/ComponentLight.cpp
  Broken Engine/Source/ComponentLight.h
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/PanelRendering.cpp
  Broken Engine/Source/PanelRendering.h
  Broken Engine/Source/ResourceShader.cpp
  Broken Engine/Source/ScriptingLighting.cpp
  Broken Engine/Source/ScriptingLighting.h
Labels: Bug

#281 Ordering scripting variables alphabetically
  Broken Engine/Source/ComponentScript.cpp
  Broken Engine/Source/ComponentScript.h
  Broken Engine/Source/ModuleScripting.cpp
Labels: Enhancement

#284 solved uniform Save&Load issue
  Broken Engine/Source/ImporterMaterial.cpp
  Broken Engine/Source/ResourceMaterial.cpp
Labels: Bug

#286 Navmesh Tiling Fix
  Broken Engine/Source/ModuleRecast.cpp
Labels: Bug, DO ASAP

#288 Variables should now be ordered when loading
  Broken Engine/Source/ComponentScript.cpp
Labels: Enhancement, Invalid

#290 solved button's texture bug
  Broken Engine/Source/ComponentButton.cpp
Labels: Bug

#292 Fixed SetRotation and GimBall Lock in Inspector
  Broken Engine/Source/ComponentAnimation.cpp
  Broken Engine/Source/ComponentCollider.cpp
  Broken Engine/Source/ComponentTransform.cpp
  Broken Engine/Source/ComponentTransform.h
  Broken Engine/Source/ScriptingTransform.cpp
Labels: Bug, High Priority

#298 Created mode Build to not add Optick
  .gitignore
  Broken Engine/Broken Engine.sln
  Broken Engine/Source/BEG.vcxproj
  Broken Engine/Source/Broken Core.vcxproj
  Broken Engine/Source/Broken Engine.vcxproj
  Broken Engine/Source/Optick/include/optick.config.h
Labels: Bug
