Repository Broken-Gem-Studio/Broken-Engine, pull requests merged in 2020-06, with the labels that each got.

#390 Particle emitters aabb
  Broken Engine/Source/ComponentParticleEmitter.cpp
  Broken Engine/Source/ComponentParticleEmitter.h
  Broken Engine/Source/ModuleParticles.cpp
Labels: Enhancement

#389 Scripting function to change UI Element position implemented
  Broken Engine/Source/AutoCompleteFileGen.cpp
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingInterface.cpp
  Broken Engine/Source/ScriptingInterface.h
Labels: Enhancement

#391 Geometry Shaders, point shadows basis
  Broken Engine/Source/ImporterShader.cpp
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/ModuleTextures.cpp
  Broken Engine/Source/ModuleTextures.h
  Broken Engine/Source/ResourceShader.cpp
  Broken Engine/Source/ResourceShader.h
Labels: Enhancement, Invalid

#393 VRAM optimization
  Broken Engine/Game/Settings/EditorResources/TextureIcon.png
  Broken Engine/Source/ImporterMaterial.cpp
  Broken Engine/Source/ModuleGui.cpp
  Broken Engine/Source/ModuleGui.h
  Broken Engine/Source/ModuleResourceManager.cpp
  Broken Engine/Source/ResourceMaterial.cpp
  Broken Engine/Source/ResourceMaterial.h
  Broken Engine/Source/ResourceTexture.cpp
Labels: Enhancement, High Priority

#395 Fixing animation function SetCurrentAnimationSpeed
  Broken Engine/Source/ComponentAnimation.cpp
Labels: Bug

#400 Fixed aspect ratio
  Broken Engine/Source/ModuleGameManager.cpp
  Broken Engine/Source/ModuleWindow.cpp
  Broken Engine/Source/PanelScene.cpp
  Broken Engine/Source/PanelScene.h
Labels: Bug, Enhancement, High Priority

#409 fixing aspect ratio
  Broken Engine/Source/ModuleGameManager.cpp
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleWindow.cpp
  Broken Engine/Source/PanelScene.cpp
Labels: Bug

#410 Outlines on materials and Toon Shader
  Broken Engine/Game/Assets/Shaders/OutlineShader.glsl
  Broken Engine/Game/Assets/Shaders/ToonShader.glsl
  Broken Engine/Source/Color.h
  Broken Engine/Source/ComponentMeshRenderer.cpp
  Broken Engine/Source/ComponentParticleEmitter.cpp
  Broken Engine/Source/ImporterMaterial.cpp
  Broken Engine/Source/ModuleRenderer3D.cpp
  Broken Engine/Source/ModuleRenderer3D.h
  Broken Engine/Source/ResourceMaterial.cpp
  Broken Engine/Source/ResourceMaterial.h
Labels: Enhancement

#411 Fixed HotReloading overwritting values
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ModuleScripting.h
  Broken Engine/Source/ScriptVar.h
Labels: Bug

#412 FreezePosition Functions
  Broken Engine/Source/AutoCompleteFileGen.cpp
  Broken Engine/Source/ModuleScripting.cpp
  Broken Engine/Source/ScriptingPhysics.cpp
  Broken Engine/Source/ScriptingPhysics.h
Labels: Invalid, invalidx2

#414 Cct fix on load scene
  Broken Engine/Source/ComponentCharacterController.cpp
Labels: Invalid, invalidx2
